### PR TITLE
docs: update readme

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by mrcjkb** [comment]
The PR title and diff don't match 🤔

**Comment by dundargoc** [comment]
Dunno what you mean. It was just a small fix, it's not important tbh. Closing.

**Comment by mrcjkb** [comment]
I'm happy to merge. Was just confused about the "update readme" title.

**Comment by dundargoc** [comment]
Nah, just a shitty low-effort PR :)

**Comment by mikavilpas** [comment]
This PR makes me happy 😄 

To add a low effort comment as a contribution, I happened to find this workflow that automates updating workflow versions https://github.com/saadmk11/github-actions-version-updater?tab=readme-ov-file

It required creating some kind of restricted access token so it was a bit involved. Here's a rough rundown
- created the token according to the instructions in the repo
- created this workflow https://github.com/mikavilpas/yazi.nvim/commit/dc7019c4c939f488450db6e7cc3dfefb1c178811, I'm hoping it will actually work and run weekly. Today I just ran it manually
- which then resulted in this PR https://github.com/mikavilpas/yazi.nvim/pull/100 that I had to manually rebase because I did stupid things before it

disclaimer: I literally found this today and don't know if there are downsides to this

**Comment by dundargoc** [comment]
@mikavilpas have you heard of dependabot? It's automatically integrated with github and is pretty decent.

**Comment by mikavilpas** [comment]
Yeah, I toggled it on in some project and it was cool. We use renovate at work which is similar.

Do you know if dependabot can upgrade github action versions?

**Comment by mikavilpas** [comment]
Oh yeah it looks like it's built in! https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

Thanks for the tip, I'll try this one out 👍🏻

**Pull request closed without merging**
